package fin.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Budget_SubstituteMenu extends SubstituteMenuBase {
  public Budget_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for Budget. Generated from implicit smart reference attribute.", new SNodePointer("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)", "1886838559406326172")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_j02my1_a(), CONCEPTS.Budget$ze));
    result.add(new SMP_Subconcepts_j02my1_b());
    return result;
  }

  public class SMP_ReferenceScope_j02my1_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_j02my1_a() {
      super(CONCEPTS.Budget$ze, LINKS.category$dGeS, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_j02my1_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_j02my1_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "Budget", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.Budget$ze);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Budget$ze = MetaAdapterFactory.getConcept(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL, "fin.structure.Budget");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink category$dGeS = MetaAdapterFactory.getReferenceLink(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL, 0x1a2f65ac41ec81b0L, "category");
  }
}
