package fin.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Account_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Budget_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Category_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new FinanceApp_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Goal_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Report_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Rule_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Transaction_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new Budget_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new Goal_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8157L), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81b3L), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81bcL), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81cfL), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec817aL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL), MetaIdFactory.conceptId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81b3L)).seal();
}
