package fin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_IncomeExpenseType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_IncomeExpenseType() {
    super(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8189L, "IncomeExpenseType", "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326153");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_income_0 = new EnumerationDescriptor.MemberDescriptor("income", "income", 0x1a2f65ac41ec818aL, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326154");
  private final EnumerationDescriptor.MemberDescriptor myMember_expense_0 = new EnumerationDescriptor.MemberDescriptor("expense", "expense", 0x1a2f65ac41ec818cL, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326156");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8189L, 0x1a2f65ac41ec818aL, 0x1a2f65ac41ec818cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_income_0, myMember_expense_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "income":
        return myMember_income_0;
      case "expense":
        return myMember_expense_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
