package fin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_BudgetPeriodType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_BudgetPeriodType() {
    super(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81a5L, "BudgetPeriodType", "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326181");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_daily_0 = new EnumerationDescriptor.MemberDescriptor("daily", "daily", 0x1a2f65ac41ec81a6L, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326182");
  private final EnumerationDescriptor.MemberDescriptor myMember_weekly_0 = new EnumerationDescriptor.MemberDescriptor("weekly", "weekly", 0x1a2f65ac41ec81a8L, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326184");
  private final EnumerationDescriptor.MemberDescriptor myMember_monthly_0 = new EnumerationDescriptor.MemberDescriptor("monthly", "monthly", 0x1a2f65ac41ec81aaL, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326186");
  private final EnumerationDescriptor.MemberDescriptor myMember_yearly_0 = new EnumerationDescriptor.MemberDescriptor("yearly", "yearly", 0x1a2f65ac41ec81abL, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326187");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81a5L, 0x1a2f65ac41ec81a6L, 0x1a2f65ac41ec81a8L, 0x1a2f65ac41ec81aaL, 0x1a2f65ac41ec81abL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_daily_0, myMember_weekly_0, myMember_monthly_0, myMember_yearly_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "daily":
        return myMember_daily_0;
      case "weekly":
        return myMember_weekly_0;
      case "monthly":
        return myMember_monthly_0;
      case "yearly":
        return myMember_yearly_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
