package fin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ReportType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ReportType() {
    super(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81c1L, "ReportType", "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326209");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_summary_0 = new EnumerationDescriptor.MemberDescriptor("summary", "summary", 0x1a2f65ac41ec81c2L, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326210");
  private final EnumerationDescriptor.MemberDescriptor myMember_category_0 = new EnumerationDescriptor.MemberDescriptor("category", "category", 0x1a2f65ac41ec81c5L, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326213");
  private final EnumerationDescriptor.MemberDescriptor myMember_monthly_0 = new EnumerationDescriptor.MemberDescriptor("monthly", "monthly", 0x1a2f65ac41ec81c7L, "r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326215");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81c1L, 0x1a2f65ac41ec81c2L, 0x1a2f65ac41ec81c5L, 0x1a2f65ac41ec81c7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_summary_0, myMember_category_0, myMember_monthly_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "summary":
        return myMember_summary_0;
      case "category":
        return myMember_category_0;
      case "monthly":
        return myMember_monthly_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
