package fin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAccount = createDescriptorForAccount();
  /*package*/ final ConceptDescriptor myConceptBudget = createDescriptorForBudget();
  /*package*/ final ConceptDescriptor myConceptCategory = createDescriptorForCategory();
  /*package*/ final ConceptDescriptor myConceptFinanceApp = createDescriptorForFinanceApp();
  /*package*/ final ConceptDescriptor myConceptGoal = createDescriptorForGoal();
  /*package*/ final ConceptDescriptor myConceptReport = createDescriptorForReport();
  /*package*/ final ConceptDescriptor myConceptRule = createDescriptorForRule();
  /*package*/ final ConceptDescriptor myConceptTransaction = createDescriptorForTransaction();
  /*package*/ final EnumerationDescriptor myEnumerationBudgetPeriodType = new EnumerationDescriptor_BudgetPeriodType();
  /*package*/ final EnumerationDescriptor myEnumerationIncomeExpenseType = new EnumerationDescriptor_IncomeExpenseType();
  /*package*/ final EnumerationDescriptor myEnumerationReportType = new EnumerationDescriptor_ReportType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAccount, myConceptBudget, myConceptCategory, myConceptFinanceApp, myConceptGoal, myConceptReport, myConceptRule, myConceptTransaction);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Account:
        return myConceptAccount;
      case LanguageConceptSwitch.Budget:
        return myConceptBudget;
      case LanguageConceptSwitch.Category:
        return myConceptCategory;
      case LanguageConceptSwitch.FinanceApp:
        return myConceptFinanceApp;
      case LanguageConceptSwitch.Goal:
        return myConceptGoal;
      case LanguageConceptSwitch.Report:
        return myConceptReport;
      case LanguageConceptSwitch.Rule:
        return myConceptRule;
      case LanguageConceptSwitch.Transaction:
        return myConceptTransaction;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationBudgetPeriodType, myEnumerationIncomeExpenseType, myEnumerationReportType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAccount() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Account", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326114");
    b.version(3);
    b.property("accountID", 0x1a2f65ac41ec8171L).type(PrimitiveTypeId.INTEGER).origin("1886838559406326129").done();
    b.property("nama", 0x1a2f65ac41ec8173L).type(PrimitiveTypeId.STRING).origin("1886838559406326131").done();
    b.property("initialBalance", 0x1a2f65ac41ec8168L).type(PrimitiveTypeId.INTEGER).origin("1886838559406326120").done();
    b.property("balance", 0x1a2f65ac41ec816dL).type(PrimitiveTypeId.INTEGER).origin("1886838559406326125").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBudget() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Budget", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326172");
    b.version(3);
    b.property("amount", 0x1a2f65ac41ec81a0L).type(PrimitiveTypeId.INTEGER).origin("1886838559406326176").done();
    b.property("period", 0x1a2f65ac41ec81a2L).type(MetaIdFactory.dataTypeId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81a5L)).origin("1886838559406326178").done();
    b.associate("category", 0x1a2f65ac41ec81b0L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L).optional(false).origin("1886838559406326192").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Category", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326134");
    b.version(3);
    b.property("nama", 0x1a2f65ac41ec8178L).type(PrimitiveTypeId.STRING).origin("1886838559406326136").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFinanceApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "FinanceApp", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8157L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326103");
    b.version(3);
    b.aggregate("accounts", 0x1a2f65ac41ec815dL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L).optional(true).ordered(true).multiple(true).origin("1886838559406326109").done();
    b.aggregate("categories", 0x1a2f65ac41ec8160L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L).optional(true).ordered(true).multiple(true).origin("1886838559406326112").done();
    b.aggregate("transactions", 0x1a2f65ac41ec81dcL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec817aL).optional(true).ordered(true).multiple(true).origin("1886838559406326236").done();
    b.aggregate("budgets", 0x1a2f65ac41ec81dfL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL).optional(true).ordered(true).multiple(false).origin("1886838559406326239").done();
    b.aggregate("reports", 0x1a2f65ac41ec81e1L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81bcL).optional(true).ordered(true).multiple(false).origin("1886838559406326241").done();
    b.aggregate("goals", 0x1a2f65ac41ec81e3L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81b3L).optional(true).ordered(true).multiple(false).origin("1886838559406326243").done();
    b.aggregate("rules", 0x1a2f65ac41ec81e5L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81cfL).optional(true).ordered(true).multiple(false).origin("1886838559406326245").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGoal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Goal", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81b3L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326195");
    b.version(3);
    b.property("targetAmount", 0x1a2f65ac41ec81b6L).type(PrimitiveTypeId.INTEGER).origin("1886838559406326198").done();
    b.property("deadline", 0x1a2f65ac41ec81b7L).type(PrimitiveTypeId.STRING).origin("1886838559406326199").done();
    b.associate("account", 0x1a2f65ac41ec81baL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L).optional(false).origin("1886838559406326202").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReport() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Report", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81bcL);
    b.class_(false, false, false);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326204");
    b.version(3);
    b.property("type", 0x1a2f65ac41ec81c0L).type(MetaIdFactory.dataTypeId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81c1L)).origin("1886838559406326208").done();
    b.associate("account", 0x1a2f65ac41ec81caL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L).optional(true).origin("1886838559406326218").done();
    b.associate("category", 0x1a2f65ac41ec81ccL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L).optional(true).origin("1886838559406326220").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Rule", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec81cfL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326223");
    b.version(3);
    b.property("condition", 0x1a2f65ac41ec81d4L).type(PrimitiveTypeId.STRING).origin("1886838559406326228").done();
    b.property("action", 0x1a2f65ac41ec81d5L).type(PrimitiveTypeId.STRING).origin("1886838559406326229").done();
    b.associate("account", 0x1a2f65ac41ec81d8L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L).optional(true).origin("1886838559406326232").done();
    b.associate("category", 0x1a2f65ac41ec81daL).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L).optional(true).origin("1886838559406326234").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransaction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("fin", "Transaction", 0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec817aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2f0d3b9-f17b-4ad0-8cde-af1798de5f0a(fin.structure)/1886838559406326138");
    b.version(3);
    b.property("type", 0x1a2f65ac41ec817cL).type(MetaIdFactory.dataTypeId(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8189L)).origin("1886838559406326140").done();
    b.property("amount", 0x1a2f65ac41ec817eL).type(PrimitiveTypeId.INTEGER).origin("1886838559406326142").done();
    b.property("date", 0x1a2f65ac41ec8180L).type(PrimitiveTypeId.STRING).origin("1886838559406326144").done();
    b.associate("fromAccount", 0x1a2f65ac41ec8191L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L).optional(true).origin("1886838559406326161").done();
    b.associate("toAccount", 0x1a2f65ac41ec8192L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8162L).optional(true).origin("1886838559406326162").done();
    b.associate("category", 0x1a2f65ac41ec8194L).target(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec8176L).optional(true).origin("1886838559406326164").done();
    return b.create();
  }
}
