package com.lang.fin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_BudgetPeriodType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_BudgetPeriodType() {
    super(0xd98c583388c34391L, 0x9525d7b106fd1bcbL, 0x7e02d173cee48a13L, "BudgetPeriodType", "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869523");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_DAILY_0 = new EnumerationDescriptor.MemberDescriptor("DAILY", "DAILY", 0x7e02d173cee48a14L, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869524");
  private final EnumerationDescriptor.MemberDescriptor myMember_WEEKLY_0 = new EnumerationDescriptor.MemberDescriptor("WEEKLY", "WEEKLY", 0x7e02d173cee48a16L, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869526");
  private final EnumerationDescriptor.MemberDescriptor myMember_MONTHLY_0 = new EnumerationDescriptor.MemberDescriptor("MONTHLY", "MONTHLY", 0x7e02d173cee48a18L, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869528");
  private final EnumerationDescriptor.MemberDescriptor myMember_YEARLY_0 = new EnumerationDescriptor.MemberDescriptor("YEARLY", "YEARLY", 0x7e02d173cee48a1aL, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869530");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xd98c583388c34391L, 0x9525d7b106fd1bcbL, 0x7e02d173cee48a13L, 0x7e02d173cee48a14L, 0x7e02d173cee48a16L, 0x7e02d173cee48a18L, 0x7e02d173cee48a1aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_DAILY_0, myMember_WEEKLY_0, myMember_MONTHLY_0, myMember_YEARLY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "DAILY":
        return myMember_DAILY_0;
      case "WEEKLY":
        return myMember_WEEKLY_0;
      case "MONTHLY":
        return myMember_MONTHLY_0;
      case "YEARLY":
        return myMember_YEARLY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
