package com.lang.fin.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ReportType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ReportType() {
    super(0xd98c583388c34391L, 0x9525d7b106fd1bcbL, 0x7e02d173cee48a1bL, "ReportType", "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869531");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_SUMMARY_0 = new EnumerationDescriptor.MemberDescriptor("SUMMARY", "SUMMARY", 0x7e02d173cee48a1cL, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869532");
  private final EnumerationDescriptor.MemberDescriptor myMember_CATEGORY_0 = new EnumerationDescriptor.MemberDescriptor("CATEGORY", "CATEGORY", 0x7e02d173cee48a1fL, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869535");
  private final EnumerationDescriptor.MemberDescriptor myMember_MONTHLY_0 = new EnumerationDescriptor.MemberDescriptor("MONTHLY", "MONTHLY", 0x7e02d173cee48a21L, "r:b0979f79-2caf-4584-b7c0-a2ec92218010(com.lang.fin.structure)/9080050094054869537");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xd98c583388c34391L, 0x9525d7b106fd1bcbL, 0x7e02d173cee48a1bL, 0x7e02d173cee48a1cL, 0x7e02d173cee48a1fL, 0x7e02d173cee48a21L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_SUMMARY_0, myMember_CATEGORY_0, myMember_MONTHLY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "SUMMARY":
        return myMember_SUMMARY_0;
      case "CATEGORY":
        return myMember_CATEGORY_0;
      case "MONTHLY":
        return myMember_MONTHLY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
