package com.lang.fin.sandbox;

/*Generated by MPS */


public class Account {
  private int accountID;
  private String nama;
  private int initialBalance;
  private int balance;

  public Account(int accountID, String nama, int initialBalance) {
    this.accountID = accountID;
    this.nama = nama;
    this.initialBalance = initialBalance;
    this.balance = initialBalance;
  }

  public void deposit(int amount) {
    balance += amount;
  }

  public void withdraw(int amount) {
    balance -= amount;
  }

  public int getAccountID() {
    return accountID;
  }


}
