package com.lang.fin.sandbox;

/*Generated by MPS */


public class Budget {
  private int amount;
  private Category category;

  public Budget(int amount, Category category) {
    this.amount = amount;
    this.category = category;

  }
}
