package fin.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Budget_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Budget_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Budget$ze, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Budget$ze = MetaAdapterFactory.getConcept(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec819cL, "fin.structure.Budget");
  }
}
