package fin.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Transaction_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Transaction_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Transaction$E4, initContext);
    record(new Amount_PD(this));
  }

  /*package*/ static final class Amount_PD extends BasePropertyConstraintsDescriptor {
    public Amount_PD(ConstraintsDescriptor container) {
      super(PROPS.amount$d6Yj, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:ee2c7ed1-ae5c-4891-a752-85fe98fa8488(fin.constraints)", "1886838559406326875"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if (propertyValue <= 0) {

        return false;
      }
      return true;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Transaction$E4 = MetaAdapterFactory.getConcept(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec817aL, "fin.structure.Transaction");
  }

  private static final class PROPS {
    /*package*/ static final SProperty amount$d6Yj = MetaAdapterFactory.getProperty(0xc753178557a44307L, 0x85796e2161aea2b8L, 0x1a2f65ac41ec817aL, 0x1a2f65ac41ec817eL, "amount");
  }
}
